<a href="https://colab.research.google.com/github/datgerhardt/madewithml101/blob/main/NumPy101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics 

In [2]:
import numpy as np

In [3]:
np.random.seed(seed=1234) # set seed for reproducibility

In [4]:
# Scalar 
x= np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim) # num of dimensions
print("x shape: ", x.shape) # dimensions
print("x size: ", x.size) # size of element
print("x dtype: ", x.dtype) # data type 

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
# Vector
x = np.array([1.3, 2.2, 17])
print("x: ", x)
print("x ndim: ", x.ndim) 
print("x shape: ", x.shape)
print("x size: ", x.size) 
print("x dtype: ", x.dtype) # take notice of this  

x:  [ 1.3  2.2 17. ]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [7]:
# Matrix
x = np.array([[1.3, 2.2], [17.9]])
print("x: ", x)
print("x ndim: ", x.ndim) 
print("x shape: ", x.shape)
print("x size: ", x.size) 
print("x dtype: ", x.dtype) # take notice of this  

x:  [list([1.3, 2.2]) list([17.9])]
x ndim:  1
x shape:  (2,)
x size:  2
x dtype:  object


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [8]:
# Matrix
x = np.array([[1.3, 2.2], [17.9,23.0]])
print("x: ", x)
print("x ndim: ", x.ndim) 
print("x shape: ", x.shape)
print("x size: ", x.size) 
print("x dtype: ", x.dtype) # take notice of this  

x:  [[ 1.3  2.2]
 [17.9 23. ]]
x ndim:  2
x shape:  (2, 2)
x size:  4
x dtype:  float64


In [10]:
# 3-D Tensor
x = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
print("x: ", x)
print("x ndim: ", x.ndim) 
print("x shape: ", x.shape)
print("x size: ", x.size) 
print("x dtype: ", x.dtype) 

x:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


# Functions

In [22]:
# Functions
print ("np.zero((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eyes((2)):\n", np.eye((2))) # identity matrix
print("np.random.random((2,2))\n", np.random.random((2,2)))

np.zero((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eyes((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2))
 [[0.21879211 0.92486763]
 [0.44214076 0.90931596]]


# Indexing

In [23]:
# Indexing 
x = np.array([1,2,3])
print("x: ", x)
print("x[0]: ", x[0])
x[0] = 0 # resigning the first index with 0
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [25]:
# Slicing or selecting part
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print("Column 1: ", x[:, 1])
print("Row 0: ", x[1,:])
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Column 1:  [ 2  6 10]
Row 0:  [5 6 7 8]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]
