<a href="https://colab.research.google.com/github/datgerhardt/ml-foundations/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
# set seed 
SEED = 1234

In [ ]:
# For reproducibility
np.random.seed(SEED)
torch.manual_seed(SEED)

# Basic

In [ ]:
# Creating a random tensor
x = torch.randn(2,3)
print(f"Type: {x.type()}")
print("x: \n",x)
print("x.shape: ", x.shape)

Type: torch.FloatTensor
x: 
 tensor([[-0.2039,  0.8738, -0.6816],
        [ 0.6339,  0.1922,  0.0918]])
x.shape:  torch.Size([2, 3])


In [ ]:
# Zeros and Ones tensors
x = torch.zeros(2,3)
print("x: \n",x)
x = torch.ones(2,3)
print("x: \n",x)

x: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
x: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# List -> Tensors
x = torch.Tensor([[1,2,3],[4,5,6]])
print(f"Size: {x.shape}")
print(f"Values: \n {x}")

Size: torch.Size([2, 3])
Values: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# NumPy -> Tensor
x = torch.Tensor(np.random.rand(2,3))
print(f"Size: {x.shape}")
print(f"Values: \n {x}")

Size: torch.Size([2, 3])
Values: 
 tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [ ]:
# Changing a type of tensor
x = torch.Tensor(2,3)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


# Operations

In [ ]:
# Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n {z}")

Size: torch.Size([2, 3])
Values: 
 tensor([[-0.6272, -0.7014, -1.2980],
        [-1.7486,  0.7907,  0.2772]])


In [ ]:
# Dot product
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n {z}")

Size: torch.Size([2, 2])
Values: 
 tensor([[-0.8448, -1.5311],
        [-1.1076,  0.1568]])


In [ ]:
# Transpose
x = torch.randn(2,3)
print(f"Size: {x.shape}")
print(f"Values: \n {x}")
y = torch.t(x)
print(f"Size of y : {y.shape}")
print(f"Values of y: \n {y}")

Size: torch.Size([2, 3])
Values: 
 tensor([[ 0.0685, -1.5104, -1.1706],
        [ 0.2259,  1.4696, -1.3284]])
Size of y : torch.Size([3, 2])
Values of y: 
 tensor([[ 0.0685,  0.2259],
        [-1.5104,  1.4696],
        [-1.1706, -1.3284]])


In [ ]:
# Reshape 
x = torch.randn(2,3)
print(f"Size: {x.shape}")
print(f"Values: \n {x}")
x = x.view(3,2)
print(f"Size: {x.shape}")
print(f"Values: \n {x}")

Size: torch.Size([2, 3])
Values: 
 tensor([[ 1.9946, -0.8209,  1.0061],
        [-1.0664, -0.4572,  0.0901]])
Size: torch.Size([3, 2])
Values: 
 tensor([[ 1.9946, -0.8209],
        [ 1.0061, -1.0664],
        [-0.4572,  0.0901]])


In [ ]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"Size: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"Size: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0),-1)
print(f"Size: {c.shape}")
print(f"c: \n{c}\n")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])



In [ ]:
# Dimension operation
x = torch.randn(2,3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}\n") 

a = torch.sum(x, dim=0) # add each row values in column 
print(f"Values: \n{a}\n") 

b = torch.sum(x, dim=1) # add each columns values in row
print(f"Values: \n{b}\n") 

Size: torch.Size([2, 3])
Values: 
tensor([[ 1.1733,  0.3714, -2.3531],
        [-1.6705, -0.4716,  0.8130]])

Values: 
tensor([-0.4972, -0.1001, -1.5401])

Values: 
tensor([-0.8084, -1.3291])



# Indexing 

In [ ]:
x = torch.randn(3,4)
print(f"x: \n{x}\n") 
print(f"x[:1]: \n{x[:1]}\n") 
print(f"x[:1, 1:3]: \n{x[:1, 1:3]}\n") 

x: 
tensor([[-1.6395, -0.8738, -0.8865, -0.8131],
        [ 0.1438, -1.5399,  0.1169, -0.1423],
        [ 0.1624,  0.4570,  1.1839,  0.8176]])

x[:1]: 
tensor([[-1.6395, -0.8738, -0.8865, -0.8131]])

x[:1, 1:3]: 
tensor([[-0.8738, -0.8865]])



# Slicing

In [ ]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim=1, index=col_indices)
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0,1])
col_indices = torch.LongTensor([0,2])
# print(row_indices, col_indices)
chosen = x[row_indices, col_indices]
print(f"Values: \n{chosen}")

Values: 
tensor([[ 0.1647,  0.2463, -0.2627],
        [-0.5241, -0.0901,  1.1621]])
Values: 
tensor([[ 0.1647, -0.2627],
        [-0.5241,  1.1621]])
Values: 
tensor([0.1647, 1.1621])


# Joining

In [ ]:
# Concatination
x = torch.randn(2,3)
print(f"Size: \n{x.shape}")
print(f"Values: \n{x}")
y = torch.cat([x,x],dim=0) # Stack by rows
print(f"Size: \n{y.shape}")
print(f"Values: \n{y}")
z = torch.cat([x,x],dim=1) # Stack by columns 
print(f"Size: \n{z.shape}")
print(f"Values: \n{z}")

Size: 
torch.Size([2, 3])
Values: 
tensor([[ 1.8637, -0.1177,  1.0928],
        [-0.9760,  0.4906, -0.2545]])
Size: 
torch.Size([4, 3])
Values: 
tensor([[ 1.8637, -0.1177,  1.0928],
        [-0.9760,  0.4906, -0.2545],
        [ 1.8637, -0.1177,  1.0928],
        [-0.9760,  0.4906, -0.2545]])
Size: 
torch.Size([2, 6])
Values: 
tensor([[ 1.8637, -0.1177,  1.0928,  1.8637, -0.1177,  1.0928],
        [-0.9760,  0.4906, -0.2545, -0.9760,  0.4906, -0.2545]])


# Gradients

In [ ]:
# Tensors with gradient bookkeeping
x = torch.randn(2,3, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()
print(f"x: \n{x}\n")
print(f"mean: {z} \n")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[-0.4744,  0.4424,  1.2949],
        [ 0.2567, -0.9681, -0.5874]], requires_grad=True)

mean: 1.9820137023925781 

x.grad: 
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])


# CUDA 

In [ ]:
# Is CUDA available?
print(torch.cuda.is_available())

False


In [ ]:
import torch

In [ ]:
# Is CUDA available?
print(torch.cuda.is_available())

True


In [ ]:
# Set device
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [ ]:
x = torch.rand(2,3)
print(x.is_cuda)
x = x.to(device)
print(x.is_cuda)

False
True


# Resouces
[Made with ml](https://madewithml.com/courses/basics/pytorch/)

[PyTorch Docs](https://pytorch.org/docs/stable/torch.html)